### ISSUE TITLE
Redirects port 80 to port 8080

### ISSUE THREAD

**Issue by aleksandarstojkovski** [pangbox/rugburn#2]
Hello, 

looking at the logs I can see that it is trying to redirect port 80 to 8080 is this behavior correct ?

ProjectG_LAN_9.exe:4480] T:24276] InternetOpenUrlA(http://patch.pangya.in.th//patch_S4/updatelist -> http://127.0.0.1:8080//patch_S4/updatelist)

Thanks,

**Comment by jchv** [comment]
Sorry I have not replied. Yeah, the default behavior in Rugburn is to redirect all HTTP requests to localhost:8080. In the past it was necessary to recompile the code to adjust the rewrite, but as of Rugburn v1.2 there is a configuration system that allows you to remove or adjust this rewrite if you wish.
